# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift_动态调用对象(实例)方法' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift_动态调用对象(实例)方法

end
